[run]
title = "Usage"
description = "To run the script, run:"
command = "python -m src.main"

[test]
title = "Testing"
description = "To run tests, use:"
command = "pytest test"

[hello]
title = "Hello"
description = "This is how a program greets the world:"
command = "echo hello world"
